import Head from "next/head";
import Image from "next/image";
import About from "../Components/About";
import Clients from "../Components/Clients";
import Landing from "../Components/Landing";
import Work from "../Components/Work";
import Services from "../Components/Services";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skapluie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <About />
      <Services />
      <Clients />
      <Work />
    </div>
  );
}
